"""add_tracking_id_phone_history

Revision ID: 237ba5d3c999
Revises: 027638a64541
Create Date: 2026-08-25 12:48:40.115301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237ba5d3c999'
down_revision: Union[str, None] = '027638a64541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    complaintstatus_enum = ENUM('SUBMITTED', 'UNDER_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='complaintstatus', create_type=False)

    op.create_table('complaint_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('old_status', complaintstatus_enum, nullable=True),
    sa.Column('new_status', complaintstatus_enum, nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_history_id'), 'complaint_history', ['id'], unique=False)
    op.add_column('complaints', sa.Column('tracking_id', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('phone_number', sa.String(), nullable=True))
    
    # Backfill tracking_ids
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE complaints SET tracking_id = 'CIV-OLD-' || id WHERE tracking_id IS NULL"))
    
    op.create_index(op.f('ix_complaints_tracking_id'), 'complaints', ['tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_tracking_id'), table_name='complaints')
    op.drop_column('complaints', 'phone_number')
    op.drop_column('complaints', 'tracking_id')
    op.drop_index(op.f('ix_complaint_history_id'), table_name='complaint_history')
    op.drop_table('complaint_history')
    # ### end Alembic commands ###
