"""Add location, OTP, and evidence fields

Revision ID: d0314047235b
Revises: da66f1e44a55
Create Date: 2026-08-23 16:50:36.667122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0314047235b'
down_revision: Union[str, None] = 'da66f1e44a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually create the enum type to support PostgreSQL
    location_source_enum = sa.Enum('GPS', 'MANUAL_PIN', 'ADDRESS_SEARCH', name='locationsource')
    location_source_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('otp_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_attempts_id'), 'otp_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_otp_attempts_phone_number'), 'otp_attempts', ['phone_number'], unique=False)
    op.create_table('complaint_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_evidence_id'), 'complaint_evidence', ['id'], unique=False)
    op.add_column('complaints', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('location_accuracy', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('location_source', location_source_enum, nullable=True))
    op.add_column('complaints', sa.Column('human_readable_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'phone_number')
    op.drop_column('complaints', 'human_readable_address')
    op.drop_column('complaints', 'location_source')
    op.drop_column('complaints', 'location_accuracy')
    op.drop_column('complaints', 'longitude')
    op.drop_column('complaints', 'latitude')
    op.drop_index(op.f('ix_complaint_evidence_id'), table_name='complaint_evidence')
    op.drop_table('complaint_evidence')
    op.drop_index(op.f('ix_otp_attempts_phone_number'), table_name='otp_attempts')
    op.drop_index(op.f('ix_otp_attempts_id'), table_name='otp_attempts')
    op.drop_table('otp_attempts')
    
    # Manually drop the enum type for PostgreSQL
    location_source_enum = sa.Enum('GPS', 'MANUAL_PIN', 'ADDRESS_SEARCH', name='locationsource')
    location_source_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
